// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: transmit.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Transmit_Transmit_FullMethodName = "/Transmit/Transmit"
)

// TransmitClient is the client API for Transmit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransmitClient interface {
	Transmit(ctx context.Context, in *TransmitRequest, opts ...grpc.CallOption) (*TransmitResponse, error)
}

type transmitClient struct {
	cc grpc.ClientConnInterface
}

func NewTransmitClient(cc grpc.ClientConnInterface) TransmitClient {
	return &transmitClient{cc}
}

func (c *transmitClient) Transmit(ctx context.Context, in *TransmitRequest, opts ...grpc.CallOption) (*TransmitResponse, error) {
	out := new(TransmitResponse)
	err := c.cc.Invoke(ctx, Transmit_Transmit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransmitServer is the server API for Transmit service.
// All implementations must embed UnimplementedTransmitServer
// for forward compatibility
type TransmitServer interface {
	Transmit(context.Context, *TransmitRequest) (*TransmitResponse, error)
	mustEmbedUnimplementedTransmitServer()
}

// UnimplementedTransmitServer must be embedded to have forward compatible implementations.
type UnimplementedTransmitServer struct {
}

func (UnimplementedTransmitServer) Transmit(context.Context, *TransmitRequest) (*TransmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transmit not implemented")
}
func (UnimplementedTransmitServer) mustEmbedUnimplementedTransmitServer() {}

// UnsafeTransmitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransmitServer will
// result in compilation errors.
type UnsafeTransmitServer interface {
	mustEmbedUnimplementedTransmitServer()
}

func RegisterTransmitServer(s grpc.ServiceRegistrar, srv TransmitServer) {
	s.RegisterService(&Transmit_ServiceDesc, srv)
}

func _Transmit_Transmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransmitServer).Transmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transmit_Transmit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransmitServer).Transmit(ctx, req.(*TransmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Transmit_ServiceDesc is the grpc.ServiceDesc for Transmit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transmit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Transmit",
	HandlerType: (*TransmitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transmit",
			Handler:    _Transmit_Transmit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transmit.proto",
}
